### ISSUE TITLE
Fails to build with rust-1.62.1

### ISSUE THREAD

**Issue by yurivict** [rustdesk/rustdesk#1163]
```
error[E0425]: cannot find function `_listen` in this scope
   --> /disk-samsung/freebsd-ports/net/rustdesk/work/rdev-fbbefd0b5d87095a7349965aec9ecd33de7035ac/src/lib.rs:272:5
    |
272 |     _listen(callback)
    |     ^^^^^^^ not found in this scope

error[E0425]: cannot find function `_simulate` in this scope
   --> /disk-samsung/freebsd-ports/net/rustdesk/work/rdev-fbbefd0b5d87095a7349965aec9ecd33de7035ac/src/lib.rs:308:5
    |
308 |     _simulate(event_type)
    |     ^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `_display_size` in this scope
   --> /disk-samsung/freebsd-ports/net/rustdesk/work/rdev-fbbefd0b5d87095a7349965aec9ecd33de7035ac/src/lib.rs:321:5
    |
321 |     _display_size()
    |     ^^^^^^^^^^^^^ not found in this scope

     Running `/disk-samsung/freebsd-ports/net/rustdesk/work/target/release/build/anyhow-f8a0b346397b225f/build-script-build`
     Running `/disk-samsung/freebsd-ports/net/rustdesk/work/target/release/build/anyhow-f8a0b346397b225f/build-script-build`
For more information about this error, try `rustc --explain E0425`.
error: could not compile `rdev` due to 3 previous errors

Caused by:
  process didn't exit successfully: `CARGO=/usr/local/bin/cargo CARGO_CRATE_NAME=rdev CARGO_MANIFEST_DIR=/disk-samsung/freebsd-ports/net/rustdesk/work/rdev-fbbefd0b5d87095a7349965aec9ecd33de7035ac CARGO_PKG_AUTHORS='Nicolas Patry <patry.nicolas@protonmail.com>' CARGO_PKG_DESCRIPTION='Listen and send keyboard and mouse events on Windows, Linux and MacOS.' CARGO_PKG_HOMEPAGE='https://github.com/Narsil/rdev' CARGO_PKG_LICENSE=MIT CARGO_PKG_LICENSE_FILE='' CARGO_PKG_NAME=rdev CARGO_PKG_REPOSITORY='https://github.com/Narsil/rdev' CARGO_PKG_VERSION=0.5.0 CARGO_PKG_VERSION_MAJOR=0 CARGO_PKG_VERSION_MINOR=5 CARGO_PKG_VERSION_PATCH=0 CARGO_PKG_VERSION_PRE='' LD_LIBRARY_PATH='/disk-samsung/freebsd-ports/net/rustdesk/work/target/release/deps:/usr/local/lib' /usr/local/bin/rustc --crate-name rdev --edition=2018 /disk-samsung/freebsd-ports/net/rustdesk/work/rdev-fbbefd0b5d87095a7349965aec9ecd33de7035ac/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no -C metadata=d3279f6f315e96a0 -C extra-filename=-d3279f6f315e96a0 --out-dir /disk-samsung/freebsd-ports/net/rustdesk/work/target/x86_64-unknown-freebsd/release/deps --target x86_64-unknown-freebsd -C linker=cc -L dependency=/disk-samsung/freebsd-ports/net/rustdesk/work/target/x86_64-unknown-freebsd/release/deps -L dependency=/disk-samsung/freebsd-ports/net/rustdesk/work/target/release/deps --extern lazy_static=/disk-samsung/freebsd-ports/net/rustdesk/work/target/x86_64-unknown-freebsd/release/deps/liblazy_static-4dca2170ab0aef65.rmeta -C link-arg=-fstack-protector-strong` (exit status: 1)
warning: build failed, waiting for other jobs to finish...
warning: `regex-syntax` (lib) generated 2 warnings (2 duplicates)
*** Error code 101
```

Version: 1.1.9
FreeBSD 13.1

**Comment by rustdesk** [comment]
FreeBSD not support yet.

**Comment by rustdesk** [comment]
But PR welcome
